### PR TITLE
Add more examples

### PR DESCRIPTION
**Pull request by Abrasha**
add following examples:
- `@Assumption`
- `@TestReporter`
- `@TestInfo`
- `@Nested`
- `@BeforeEach`

---
I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by marcphilipp** [comment]
Thanks! 👍

**Comment by Abrasha** [comment]
@marcphilipp, I have a question regarding file headers(license). The specified years are 2015-2016. Should they be changed to 2015-2017?

**Comment by sbrannen** [comment]
Guys, I disapprove of the merging of this PR.

See my comments in commit 05be286d00ec0919dc895dafca46ff2523ae7079.

**Comment by sbrannen** [comment]
Regarding copyright dates, yes, they must be updated to 2017 for any code submitted in 2017.

**Comment by sbrannen** [comment]
Furthermore, do we really want to provide and maintain an additional set of examples in this repository that compete with those in the User Guide, especially when the existing examples in the User Guide are more thorough than those proposed here?

**Comment by marcphilipp** [comment]
Point taken. In hindsight, my decision to merge it was a bit hasty. Maybe we should revert it and rather clarify that these projects' purpose is to demonstrate build tool setup as opposed to providing a comprehensive set of examples and add a link to the User Guide.

**Comment by sbrannen** [comment]
> Maybe we should revert it and rather clarify that these projects' purpose is to demonstrate build tool setup as opposed to providing a comprehensive set of examples and add a link to the User Guide.

Yes, I think that would be the best course of action!

**Comment by sbrannen** [comment]
I just noticed that the newly introduced tests also print to `System.out` as well. :(

**Comment by sbrannen** [comment]
I'll go ahead and revert the commit.

**Comment by sbrannen** [comment]
Affected commits have been reverted in `master`.

**Comment by Abrasha** [comment]
@sbrannen Thanks you for notices

**Comment by sbrannen** [comment]
@Abrasha, you're welcome.

And more importantly, even though I reverted your proposal, I want to thank you for taking the time to contribute to the project!

We truly appreciate help from the community.

And... if you feel that the examples in the User Guide are lacking, please make suggestions on how to improve them within the `junit5` repository (https://github.com/junit-team/junit5).

Cheers!

**Comment by sbrannen** [comment]
FYI: I have added links to to the User Guide in the Gradle and Maven sample projects.

**Comment by marcphilipp** [comment]
Thanks, Sam! 👍

**Pull request closed without merging**
