### PR TITLE
Add junit5-jupiter-starter-maven-kotlin sample #70 #102

### PR DESCRIPTION
**Pull request by daggerok**
This PR contains junit5-jupiter-starter-maven-kotlin sample.

Given project allows mix java and Kotlin test classes together by using JUnit 5 Jupiter and JUnit 4 Vintage test engines. 

That PR was added in scope of existing Create "missing" samples #70 GitHub issue.

## Overview

- contains wrapper (maven version: 3.6.1)
- supports java 1.8 (see `pom-java8.xml` file) as well as java 11
- using latest Jupiter versions at the moment and latest stable Kotlin available in maven central

---
I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by daggerok** [comment]
Hello @sormuras,

I have applied your review comments. Please let me know if I missed something

---
Regards

**Comment by daggerok** [comment]
Squashed commits

**Comment by daggerok** [comment]
Please review

**Comment by sormuras** [comment]
Thanks @daggerok!

**Comment by sormuras** [comment]
@daggerok -- do you want to take over #104 and/or #105 as well? ;-)

**Comment by daggerok** [comment]
Hey @sormuras,
Yes, I can take a look on it this weekend

**Comment by sormuras** [comment]
That'd be awesome.

**Pull request merged**
