### PR TITLE
Upgrade maven-surefire-plugin version to 2.20.1

### PR DESCRIPTION
**Pull request by eddumelendez**
See gh-23

## Overview

- Upgrade `maven-surefire-plugin` version and remove `includes` in `configuration` section since the plugin provides `**/*Tests.java`

---
I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by marcphilipp** [comment]
Surefire 2.20 has a criticial bug that produces an OutOfMemoryError in some cases. Thus, we've just reverted to 2.19.1 in the main repo (see https://github.com/junit-team/junit5/issues/809#issuecomment-309232038). Thus, I would like to wait to recommend using 2.20 until 2.20.1 is released.

Regarding `**/*Tests.java`: Which version of Surefire started supporting that by default?

**Comment by eddumelendez** [comment]
> Regarding **/*Tests.java: Which version of Surefire started supporting that by default?

Since version `2.20`. See [SUREFIRE-1260](https://issues.apache.org/jira/browse/SUREFIRE-1260)

**Comment by sbrannen** [comment]
@eddumelendez, if you change the Surefire version to `2.20.1` and force push the changes, I think we could merge this PR.

**Comment by sbrannen** [comment]
Changed issue title accordingly.

**Comment by eddumelendez** [comment]
I got this error after the upgrade

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project junit5-maven-consumer: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/eddumelendez/Documents/Git/junit5-samples/junit5-maven-consumer/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] org.apache.maven.surefire.report.RunListener.testSetStarting(Lorg/apache/maven/surefire/report/ReportEntry;)V
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org.apache.maven.surefire.report.RunListener.testSetStarting(Lorg/apache/maven/surefire/report/ReportEntry;)V
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:673)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:280)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by sormuras** [comment]
It can't find any tests: https://travis-ci.org/junit-team/junit5-samples/jobs/276844959#L516

**Comment by sormuras** [comment]
Same if leave the

	<includes>
		<include>**/Test*.java</include>
		<include>**/*Test.java</include>
		<include>**/*Tests.java</include>
		<include>**/*TestCase.java</include>
	</includes>

intact: https://travis-ci.org/junit-team/junit5-samples/jobs/276980602

**Comment by Tibor17** [comment]
Yes please adapt to the changed signature in RunListener. Two methods changed with method parameter type.

**Comment by sbrannen** [comment]
FYI: I just verified that our current snapshots work fine with Surefire 2.20.1.

See https://github.com/junit-team/junit5/issues/809#issuecomment-330539346 for details.

**Comment by sbrannen** [comment]
We will unfortunately have to postpone the upgrade until after JUnit Platform 1.1 has been released, since we do not want to have the sample projects building against snapshots.

Sorry, @eddumelendez! 😞

**Comment by marcphilipp** [comment]
Support for 2.20.1 had to be rolled back. JUnit Platform 1.2 will support 2.21, though.

**Pull request closed without merging**
