### PR TITLE
deps: upgrade gradle to 8.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
## Overview

- upgrade gradle to 8.1

---
I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by marcphilipp** [comment]
@chenrui333 Did you mean to update to 8.0.1?

**Comment by chenrui333** [comment]
yeah, you are right 😅

**Comment by chenrui333** [comment]
@marcphilipp any thoughts about merging this PR?

**Comment by chenrui333** [comment]
gentle ping @marcphilipp

**Review by sormuras — APPROVED** [review]
LGTM

**Review by marcphilipp — APPROVED** [review]

**Pull request merged**
