### PR TITLE
fix: adds support to latest `maven`

### PR DESCRIPTION
**Pull request by lx-931203**
fixes: https://github.com/junit-team/junit5-samples/issues/89

## Overview
Simply updates `Maven Surefire` plugin.

I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by sormuras** [comment]
Mh, indentation still looks "off". Please have a look at https://github.com/junit-team/junit5-samples/pull/90/files and align the lines using tabs. Thanks!

**Comment by sormuras** [comment]
...in a few weeks, methinks.

**Comment by Tibor17** [comment]
@marcphilipp 
I won't take weeks to release 3.0.0.
There was a big plan with this version years ago and we still have a lot to do.
Therefore a lot to do because we still have to break some compatibility and that's the way how we would fix critical bugs and introduce extensions. But I do not know what you was asking for, because we still have a pure support of JUnit5 features in Surefire project. We are missing properly working parallelism, customized description name and I am awaiting dynamic resolution or discovery of engine version and we still do not have it.

**Comment by marcphilipp** [comment]
Thanks for chiming in, @Tibor17! This PR was motivated by #89. I'll close it for now, since we'll wait for a bug fix release or 3.0.0.

**Comment by Tibor17** [comment]
@marcphilipp 
I fully respect your decision. If you are fine with `2.22.1` use it, no problem at all.
From my side, I can only say that the milestone `3.0.0` is a big chance for us to make such changes which could not be done in 2.x. Latest in transition to 3.0 but it is so much work which had to be split in multiple release candidates and getting feedback from the users. That's the only way we could do.

**Pull request closed without merging**
