### PR TITLE
Remove unused property junit.platform.version

### PR DESCRIPTION
**Pull request by britter**
## Overview

Property is not used and can be dropped.

---
I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by sbrannen** [comment]
This has been merged into `master`.

Thanks

**Comment by sormuras** [comment]
That was not `master`, that was `r5.3.0`.

**Comment by sbrannen** [comment]
oops!

How did that happen? 😲

**Comment by sbrannen** [comment]
Well, I guess it's not the end of the world having that in the r5.3.0 branch.

So I'll leave it there, unless anyone thinks we should revert that.

And I'll cherry pick to `master`.

**Comment by britter** [comment]
I probably messed up the PR because I did the change via the GitHub UI 😇

**Comment by sbrannen** [comment]
No worries. The change is in `master` now as well.

**Pull request merged**
