### PR TITLE
Build samples using JUnit 5 SNAPSHOT artifacts

### PR DESCRIPTION
**Pull request by sormuras**
## Overview

Building samples using JUnit 5 SNAPSHOT artifacts ensures we don't break basic functionality. 

## TODO
- [ ] Add `build-SNAPSHOT.gradle` to all Gradle-based samples
- [ ] Add `pom-SNAPSHOT.xml` to all Maven-based samples
- [ ] Beautify Travis CI build script using matrix/stage combination

---
I hereby agree to the terms of the JUnit Contributor License Agreement.

### CODE REVIEW

**Comment by sormuras** [comment]
Using https://docs.travis-ci.com/user/cron-jobs/ on weekly schedule would ensure that we do stay in sync with the master branch of the main project.

**Comment by sbrannen** [comment]
Why not nightly instead of weekly?

**Comment by sormuras** [comment]
Austerity. Some days nothing changes over at the main project, no need to build the sample against the unchanged master branch then.
An on-change trigger that builds this downstream projects would be the best solution.

**Comment by sormuras** [comment]
Superseded by https://github.com/junit-team/junit5-samples/commit/c32449cec994763bf37d99b268d479427c2987b0

**Comment by sbrannen** [comment]
>  An on-change trigger that builds this downstream projects would be the best solution.

Yes, I totally agree with that! 👍

**Pull request closed without merging**
